# Generated by Django 6.0 on 2026-01-25 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'актер',
                'verbose_name_plural': 'актеры',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'режиссер',
                'verbose_name_plural': 'режиссеры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888, message='Первый фильм был снят в 1888 году'), django.core.validators.MaxValueValidator(2027, message='Год не может быть в будущем')], verbose_name='Год премьеры')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('duration', models.IntegerField(blank=True, help_text='Длительность в минутах', null=True, verbose_name='Длительность (мин)')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна')),
                ('actors', models.ManyToManyField(related_name='acted_movies', to='movies.actor', verbose_name='Актеры')),
                ('directors', models.ManyToManyField(related_name='directed_movies', to='movies.director', verbose_name='Режиссеры')),
                ('genres', models.ManyToManyField(related_name='genre_movies', to='movies.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'фильмы',
                'ordering': ['-release_year', 'title'],
            },
        ),
    ]
